targets:
  $default:
    builders:
      freezed:
        enabled: true
        options:
          format: true
          map:
            map: false
            map_or_null: false
            maybe_map: false
          when:
            when: false
            when_or_null: false
            maybe_when: false

      json_serializable:
        options:
          explicit_to_json: true