name: interfaces
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.9.0

dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.7.0
  custom_lint: any
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  injectable_generator: ^2.8.1
  leancode_lint: ^18.0.0

scripts:
  gen:
    dart run build_runner build --delete-conflicting-outputs;
    dart pub get;
  upgrade:
    dart pub upgrade --major-versions;
  fix:
    dart fix --apply;
    dart format bin lib;

